import mongoose from "mongoose";

const lotSchema = new mongoose.Schema(
  {
    // TODO : right now the Lot_id column is autogenerated by mongodb with '_id' key later we change it to lot_id.
    trade_id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Trade",
      required: true,
    },
    stock_name: { type: String, required: true },
    lot_quantity: { type: Number, required: true },
    realized_quantity: { type: Number, default: 0 },
    realized_trade_id: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Trade",
      },
    ],
    lot_status: {
      type: String,
      enum: ["OPEN", "PARTIALLY_REALIZED", "FULLY_REALIZED"],
      default: "OPEN",
    },
    price: { type: Number, required: true },
  },
  { timestamps: true }
);

const Lot = mongoose.model("Lot", lotSchema);

export default Lot;