import mongoose from "mongoose";

const tradeSchema = new mongoose.Schema(
  {
    //TODO: right now the trade_id column is autogenerated by mongodb with '_id' key later we change it to trade_id.
    stock_name: {
      type: String,
      required: [true, "Stock name is required"],
    },
    quantity: {
      type: Number,
      required: [true, "Quantity is required"],
      validate: {
        validator: Number.isInteger,
        message: "{VALUE} is not an integer value",
      },
    },
    broker_name: {
      type: String,
      required: [true, "Broker name is required"],
    },
    price: {
      type: Number,
      required: [true, "Price is required"],
      min: [0, "Price must be positive"],
    },
    amount: { type: Number },
    timestamp: { type: Date, default: Date.now },
  },
  { timestamps: true }
);

tradeSchema.pre("save", function (next) {
  this.amount = this.price * Math.abs(this.quantity);
  next();
});

const Trade = mongoose.model("Trade", tradeSchema);

export default Trade;
